o1-labs/mina-rust

snarker/src/action_kind.rs
snarker/src/consensus/consensus_actions.rs
snarker/src/consensus/consensus_effects.rs
snarker/src/consensus/consensus_reducer.rs
snarker/src/consensus/consensus_state.rs
snarker/src/consensus/mod.rs
tests/files/forks/long-keep-density-161-166-3NKY1kxHMRfjBbjfAA5fsasUCWFF9B7YqYFfNH4JFku6ZCUUXyLG-3NLFoBQ6y3nku79LQqPgKBmuo5Ngnpr7rfZygzdRrcPtz2gewRFC-cnd.json
tests/files/forks/long-keep-density-161-166-3NKY1kxHMRfjBbjfAA5fsasUCWFF9B7YqYFfNH4JFku6ZCUUXyLG-3NLFoBQ6y3nku79LQqPgKBmuo5Ngnpr7rfZygzdRrcPtz2gewRFC-tip.json
tests/files/forks/long-take-density-92-97-3NLESd9gzU52bDWSXL5uUAYbCojHXSVdeBX4sCMF3V8Ns9D1Sriy-3NLQfKJ4kBagLgmiwyiVw9zbi53tiNy8TNu2ua1jmCyEecgbBJoN-cnd.json
tests/files/forks/long-take-density-92-97-3NLESd9gzU52bDWSXL5uUAYbCojHXSVdeBX4sCMF3V8Ns9D1Sriy-3NLQfKJ4kBagLgmiwyiVw9zbi53tiNy8TNu2ua1jmCyEecgbBJoN-tip.json
tests/files/forks/short-keep-vrf-117-117-3NLWvDBFYJ2NXZ1EKMZXHB52zcbVtosHPArn4cGj8pDKkYsTHNnC-3NKLEnUBTAhC95XEdJpLvJPqAUuvkC176tFKyLDcXUcofXXgQUvY-cnd.json
tests/files/forks/short-keep-vrf-117-117-3NLWvDBFYJ2NXZ1EKMZXHB52zcbVtosHPArn4cGj8pDKkYsTHNnC-3NKLEnUBTAhC95XEdJpLvJPqAUuvkC176tFKyLDcXUcofXXgQUvY-tip.json
tests/files/forks/short-take-length-60-61-3NLQEb5mXqXCL34rueHrMkUVyWSQ7aYjvi6K98ZdpEnTozef69uR-3NKuw8mvieV9RLpdRmHb4kxg7NWR83TfwzNkVmJCeHUmVWFdUQCp-cnd.json
tests/files/forks/short-take-length-60-61-3NLQEb5mXqXCL34rueHrMkUVyWSQ7aYjvi6K98ZdpEnTozef69uR-3NKuw8mvieV9RLpdRmHb4kxg7NWR83TfwzNkVmJCeHUmVWFdUQCp-tip.json
tests/files/forks/short-take-vrf-99-99-3NL4kAA33FRs9K66GvVNupNT94L4shALtYLHJRfmxhdZV8iPg2pi-3NKC9F6mgtvRiHgYxiPBt1P5QDYaPVpD3YWyJhjmJZkNnT7RYitm-cnd.json
tests/files/forks/short-take-vrf-99-99-3NL4kAA33FRs9K66GvVNupNT94L4shALtYLHJRfmxhdZV8iPg2pi-3NKC9F6mgtvRiHgYxiPBt1P5QDYaPVpD3YWyJhjmJZkNnT7RYitm-tip.json

I've added long range fork handling. Also I've introduced an intermediate state for fork range detection.
I'm going to collect block pairs for different forks (both long and short ranges) and add them along with tests.
Re: #5 
Fix: #31

Long range fork resolution

---

.drone.yml
Dockerfile
cli/src/commands/snarker/ext_snark_worker.rs
node/shared/src/log.rs
p2p/src/identity/peer_id.rs
snarker/src/action_kind.rs
snarker/src/effects.rs
snarker/src/event_source/event_source_effects.rs
snarker/src/external_snark_worker/external_snark_worker_actions.rs
snarker/src/external_snark_worker/external_snark_worker_effects.rs
snarker/src/external_snark_worker/external_snark_worker_errors.rs
snarker/src/external_snark_worker/external_snark_worker_impls.rs
snarker/src/external_snark_worker/external_snark_worker_reducer.rs
snarker/src/external_snark_worker/external_snark_worker_state.rs
snarker/src/external_snark_worker/mod.rs
snarker/src/ledger/ledger_service.rs
snarker/src/logger/logger_effects.rs
snarker/src/rpc/mod.rs
snarker/src/rpc/rpc_effects.rs
snarker/src/rpc/rpc_impls.rs
snarker/src/snark_pool/snark_pool_effects.rs
snarker/src/snark_pool/snark_pool_state.rs
snarker/src/state.rs

task(snarker/ext): improve events logging

---

node/src/event_source/event_source_effects.rs
node/src/snark_pool/snark_pool_effects.rs
p2p/src/channels/p2p_channels_service.rs
p2p/src/channels/snark/p2p_channels_snark_actions.rs
p2p/src/channels/snark/p2p_channels_snark_effects.rs
p2p/src/p2p_event.rs
p2p/src/service_impl/libp2p/mod.rs
p2p/src/service_impl/webrtc_with_libp2p.rs

fix(p2p): Avoid custom encoding for gossipsub

---

node/native/src/http_server.rs
node/native/src/rpc.rs
node/src/action_kind.rs
node/src/event_source/event.rs
node/src/event_source/event_source_effects.rs
node/src/rpc/mod.rs
node/src/rpc/rpc_actions.rs
node/src/rpc/rpc_effects.rs
node/src/rpc/rpc_reducer.rs
node/src/rpc/rpc_service.rs
node/src/stats/mod.rs
node/testing/src/service/rpc_service.rs

feat(health): implement healthz RPC

---

.github/workflows/daily.yaml
README.md
helm/openmina/templates/service.yaml
testing.md

- Checks that previous daily deployment is stable
- Checks that block height is the same as in berkeleynet
- Adds badges
Re: #97

test(berkeley): Add stability test

---

.drone.yml
cli/src/commands/node/mod.rs
node/native/src/service.rs
node/src/config.rs
node/src/service.rs
node/src/snark_pool/mod.rs
node/src/snark_pool/snark_pool_effects.rs
node/src/snark_pool/snark_pool_service.rs
node/testing/src/service/mod.rs

ci(drone): fix test failing because p2p connections are attempted on webrtc transport 

---

scan-state.md
snark-work.md
why-openmina.md

@JanSlobodnik Collected and based your commits on develop.

Add documentation

---

ledger/src/scan_state/conv.rs
ledger/src/scan_state/parallel_scan.rs
ledger/src/scan_state/scan_state.rs
ledger/src/staged_ledger/staged_ledger.rs
ledger/src/verifier/mod.rs

Optimization: Reduce memory usage by removing data duplication across scan states 

---

ledger/src/scan_state/conv.rs
node/src/account/public_key.rs
node/testing/src/cluster/mod.rs
node/testing/src/main.rs
node/testing/src/node/rust/config.rs
node/testing/src/scenarios/cluster_runner.rs
node/testing/src/scenarios/simulation/small.rs
node/testing/src/scenarios/solo_node/sync_to_genesis.rs
node/testing/src/service/mod.rs
node/testing/src/simulator/config.rs
node/testing/src/simulator/mod.rs

Integrate snark worker node into testing simulator, so that we can produce snarks, fill and commit scan state

---

node/src/ledger/ledger_service.rs

When a staged ledger hash mismatch occurs, dump the staged ledger + block to a file so we can easily reproduce the bug in Rust and OCaml: https://github.com/openmina/openmina/blob/8e68037aafddd43842a54c8439baeafee4c6e1eb/ledger/src/staged_ledger/staged_ledger.rs#L5959

Save `StagedLedger` and block to a file, when the block application fail

---

.drone.yml
.github/workflows/ci.yaml
Dockerfile
README.md
ledger/.github/workflows/rust-tests.yml
node/testing/docker/Dockerfile.openmina
node/testing/docker/Dockerfile.test
run.yaml

Use Rust 1.75 everywhere on CI.

ci: Set Rust version to 1.75 everywhere

---

README.md
frontend/README.md

Just so that we have the updated READMEs on `main` too.

Medge `develop` into `main` (docs)

---

Cargo.lock
node/testing/src/scenarios/driver.rs
p2p/src/channels/rpc/p2p_channels_rpc_actions.rs
tools/bootstrap-sandbox/src/client.rs

Compilation was fixed in https://github.com/openmina/openmina/pull/222 but failed again after https://github.com/openmina/openmina/pull/245.
\+ Run `cargo fmt`

Fix compile + format code

---

Cargo.lock

fix(p2p): update redux dependency

---

mina-p2p-messages/src/v2/manual.rs
vrf/src/output.rs

Also including a small fix - truncate the test file to 1 line

Fix VRF output conversion to mina type + serialization fix

---

cli/src/commands/node/mod.rs
node/src/action_kind.rs
node/src/logger/logger_effects.rs
node/src/p2p/network/mod.rs
p2p/src/channels/rpc/mod.rs
p2p/src/channels/rpc/p2p_channels_rpc_actions.rs
p2p/src/channels/rpc/p2p_channels_rpc_effects.rs
p2p/src/network/noise/p2p_network_noise_actions.rs
p2p/src/network/noise/p2p_network_noise_effects.rs
p2p/src/network/noise/p2p_network_noise_reducer.rs
p2p/src/network/noise/p2p_network_noise_state.rs
p2p/src/network/rpc/p2p_network_rpc_actions.rs
p2p/src/network/rpc/p2p_network_rpc_effects.rs
p2p/src/network/rpc/p2p_network_rpc_reducer.rs
p2p/src/network/scheduler/p2p_network_scheduler_reducer.rs
p2p/src/network/select/p2p_network_select_effects.rs

Implement response for incoming RPC requests. Make openmina able to bootstrap other nodes.
Fixed few bugs in handshake.

Serve incoming bootstrap

---

mina-p2p-messages/src/rpc.rs
mina-p2p-messages/src/rpc_kernel.rs
mina-p2p-messages/src/v1/generated.rs
mina-p2p-messages/src/versioned.rs
mina-p2p-messages/tests/decode_bench.rs
mina-p2p-messages/tests/rpc-read.rs
node/src/transition_frontier/sync/transition_frontier_sync_reducer.rs
p2p/libp2p-rpc-behaviour/src/behaviour.rs
p2p/libp2p-rpc-behaviour/src/handler.rs
p2p/libp2p-rpc-behaviour/src/state.rs
p2p/libp2p-rpc-behaviour/src/stream.rs
p2p/src/channels/rpc/mod.rs
p2p/src/network/rpc/p2p_network_rpc_effects.rs
p2p/src/network/rpc/p2p_network_rpc_reducer.rs
p2p/src/network/rpc/p2p_network_rpc_state.rs
p2p/src/service_impl/libp2p/behavior.rs
p2p/src/service_impl/libp2p/mod.rs
tools/bootstrap-sandbox/src/client.rs
tools/bootstrap-sandbox/src/replay.rs

- Add best_tip to TF chain
- Fix pending RPC handling for peer disconnection
- Better RPC errors handling

fix(bootstrap): TF sync + RPC fixes

---

frontend/src/app/features/dashboard/dashboard-blocks-sync/dashboard-blocks-sync.component.html
frontend/src/app/features/dashboard/dashboard-blocks-sync/dashboard-blocks-sync.component.ts
frontend/src/app/features/dashboard/dashboard-errors/dashboard-errors.component.ts
frontend/src/app/features/dashboard/dashboard-ledger/dashboard-ledger.component.html
frontend/src/app/features/dashboard/dashboard-ledger/dashboard-ledger.component.scss
frontend/src/app/features/dashboard/dashboard-ledger/dashboard-ledger.component.ts
frontend/src/app/features/dashboard/dashboard-network/dashboard-network.component.html
frontend/src/app/features/dashboard/dashboard-network/dashboard-network.component.scss
frontend/src/app/features/dashboard/dashboard-network/dashboard-network.component.ts
frontend/src/app/features/dashboard/dashboard-transition-frontier/dashboard-transition-frontier.component.html
frontend/src/app/features/network/bootstrap-stats/network-bootstrap-stats.service.ts
frontend/src/app/features/network/bootstrap-stats/side-panel/network-bootstrap-stats-side-panel.component.ts
frontend/src/app/features/network/bootstrap-stats/table/network-bootstrap-stats-table.component.html
frontend/src/app/features/network/bootstrap-stats/table/network-bootstrap-stats-table.component.ts
frontend/src/app/features/network/dht-graph/network-dht-graph-binary-tree/equal-distance-algorithm.ts
frontend/src/app/features/network/dht-graph/network-dht-graph-binary-tree/minimum-distance-algorithm.ts
frontend/src/app/features/network/dht-graph/network-dht-graph-binary-tree/network-dht-graph-binary-tree.component.html
frontend/src/app/features/network/dht-graph/network-dht-graph-binary-tree/network-dht-graph-binary-tree.component.scss
frontend/src/app/features/network/dht-graph/network-dht-graph-binary-tree/network-dht-graph-binary-tree.component.ts
frontend/src/app/shared/loading-spinner/loading-spinner.component.html
frontend/src/app/shared/loading-spinner/loading-spinner.component.scss
frontend/src/app/shared/loading-spinner/loading-spinner.component.ts
frontend/src/app/shared/types/network/bootstrap-stats/network-bootstrap-stats-request.type.ts

Frontend Dashboard changes

---

.github/workflows/ci.yaml
node/src/rpc/rpc_effects.rs

task(ci): bootstrap in ci

---

.drone.yml
frontend/.drone.yml
frontend/package-lock.json
frontend/package.json
frontend/src/app/app.routing.ts
frontend/src/app/features/block-production/block-production.component.html
frontend/src/app/features/block-production/block-production.component.ts
frontend/src/app/features/block-production/block-production.module.ts
frontend/src/app/features/block-production/block-production.routing.ts
frontend/src/app/features/block-production/overview/block-production-overview.component.html
frontend/src/app/features/block-production/overview/block-production-overview.component.ts
frontend/src/app/features/block-production/overview/block-production-overview.module.ts
frontend/src/app/features/block-production/overview/block-production-overview.routing.ts
frontend/src/app/features/block-production/overview/block-production-overview.service.ts
frontend/src/app/features/block-production/overview/block-production-slots/block-production-slots.component.html
frontend/src/app/features/block-production/overview/block-production-slots/block-production-slots.component.ts
frontend/src/app/features/network/bootstrap-stats/table/network-bootstrap-stats-table.component.html
frontend/src/app/features/network/bootstrap-stats/table/network-bootstrap-stats-table.component.ts
frontend/src/app/layout/menu/menu.component.ts
frontend/src/app/shared/types/core/environment/mina-env.type.ts
frontend/src/environments/environment.ts
frontend/tsconfig.json

Docker Reference changes for Frontend

Frontend Docker image renaming

---

.github/workflows/ci.yaml
node/src/action_kind.rs
node/testing/src/node/rust/config.rs
node/testing/src/scenarios/driver.rs
node/testing/src/scenarios/multi_node/vrf_correct_ledgers.rs
node/testing/src/scenarios/multi_node/vrf_epoch_bounds_correct_ledgers.rs
node/testing/src/scenarios/p2p/basic_connection_handling.rs
node/testing/src/scenarios/p2p/basic_incoming_connections.rs
node/testing/src/scenarios/p2p/basic_outgoing_connections.rs
node/testing/src/service/mod.rs
node/testing/tests/p2p_basic_connections.rs
node/testing/tests/p2p_basic_outgoing.rs
p2p/src/connection/incoming/mod.rs
p2p/src/connection/outgoing/mod.rs
p2p/src/connection/outgoing/p2p_connection_outgoing_effects.rs
p2p/src/disconnection/p2p_disconnection_effects.rs
p2p/src/lib.rs
p2p/src/network/noise/mod.rs
p2p/src/network/noise/p2p_network_noise_effects.rs
p2p/src/network/noise/p2p_network_noise_reducer.rs
p2p/src/network/noise/p2p_network_noise_state.rs
p2p/src/network/p2p_network_reducer.rs
p2p/src/network/scheduler/p2p_network_scheduler_actions.rs
p2p/src/network/scheduler/p2p_network_scheduler_effects.rs
p2p/src/network/scheduler/p2p_network_scheduler_reducer.rs
p2p/src/network/scheduler/p2p_network_scheduler_state.rs
p2p/src/p2p_config.rs
p2p/src/p2p_state.rs

Fix existing p2p tests

---

mina-p2p-messages/src/array.rs
mina-p2p-messages/src/b58.rs
mina-p2p-messages/src/bigint.rs
mina-p2p-messages/src/char.rs
mina-p2p-messages/src/core.rs
mina-p2p-messages/src/gossip.rs
mina-p2p-messages/src/hash_input.rs
mina-p2p-messages/src/lib.rs
mina-p2p-messages/src/list.rs
mina-p2p-messages/src/number.rs
mina-p2p-messages/src/rpc.rs
mina-p2p-messages/src/rpc_kernel.rs
mina-p2p-messages/src/string.rs
mina-p2p-messages/src/utils.rs
mina-p2p-messages/src/versioned.rs
mina-p2p-messages/tests/binprot-read.rs
mina-p2p-messages/tests/binprot-rs.rs
mina-p2p-messages/tests/decode_alloc.rs
mina-p2p-messages/tests/jsonify.rs
mina-p2p-messages/tests/rpc-read.rs
p2p/src/service_impl/libp2p/mod.rs

Also disabled clippy for generated code. Need more time to fix that too (and ditch v1 types).

task(clippy): Fix clippy for p2p messages

---

.github/workflows/ci.yaml
p2p/src/network/scheduler/p2p_network_scheduler_effects.rs
p2p/src/network/scheduler/p2p_network_scheduler_reducer.rs

fix(libp2p): propagate error on reading

---

.github/workflows/ci.yaml
p2p/src/network/identify/stream/p2p_network_identify_stream_effects.rs

Probe node readiness several times

task(tests): ensure node is bootstrapped

---

.github/workflows/ci.yaml
p2p/src/channels/best_tip/p2p_channels_best_tip_effects.rs
p2p/src/channels/snark/p2p_channels_snark_effects.rs
p2p/src/network/pubsub/p2p_network_pubsub_actions.rs
p2p/src/p2p_actions.rs

Also re-enable clippy check for enum variant sizes and remove stack increase config from test.

fix(p2p): Reduce action size.

---

p2p/tests/connection.rs

fix(tests): fix stop condition for libp2p node

---

p2p/src/network/kad/request/p2p_network_kad_request_effects.rs
p2p/src/peer/p2p_peer_actions.rs
p2p/testing/src/event.rs
p2p/tests/kademlia.rs

fix(kad): respect local addrs filtering

---

.github/workflows/ci.yaml
node/src/action_kind.rs
p2p/src/network/identify/stream/p2p_network_identify_stream_effects.rs
p2p/src/network/kad/stream/p2p_network_kad_stream_effects.rs
p2p/src/network/mod.rs
p2p/src/network/p2p_network_reducer.rs
p2p/src/network/pubsub/p2p_network_pubsub_effects.rs
p2p/src/network/rpc/p2p_network_rpc_effects.rs
p2p/src/network/scheduler/p2p_network_scheduler_actions.rs
p2p/src/network/scheduler/p2p_network_scheduler_effects.rs
p2p/src/network/scheduler/p2p_network_scheduler_reducer.rs
p2p/src/network/select/p2p_network_select_actions.rs
p2p/src/network/select/p2p_network_select_effects.rs
p2p/src/network/yamux/mod.rs
p2p/src/network/yamux/p2p_network_yamux_actions.rs
p2p/src/network/yamux/p2p_network_yamux_effects.rs
p2p/src/network/yamux/p2p_network_yamux_state.rs
p2p/src/p2p_config.rs

fix(p2p): stream select error handling

---

node/src/ledger/ledger_service.rs

Fix genesis snarked mask getting overwritten

---

ARCHITECTURE.md
Cargo.lock
Cargo.toml
node/src/consensus/consensus_reducer.rs
node/src/snark_pool/candidate/snark_pool_candidate_reducer.rs
node/src/snark_pool/snark_pool_reducer.rs

Future-proofing for serialized callbacks support in the WASM target

fix: Use explicitly named callbacks

---

Cargo.lock
cli/replay_dynamic_effects/Cargo.toml
node/src/action_kind.rs
node/testing/src/scenarios/p2p/basic_connection_handling.rs
p2p/src/network/p2p_network_reducer.rs
p2p/src/network/p2p_network_state.rs
p2p/src/network/rpc/p2p_network_rpc_actions.rs
p2p/src/network/rpc/p2p_network_rpc_effects.rs
p2p/src/network/rpc/p2p_network_rpc_reducer.rs
p2p/src/network/rpc/p2p_network_rpc_state.rs
p2p/src/p2p_effects.rs
p2p/src/p2p_reducer.rs
p2p/src/service_impl/webrtc_with_libp2p.rs

Fix p2p rpcs time out

---

p2p/src/network/noise/p2p_network_noise_effects.rs
p2p/src/network/noise/p2p_network_noise_reducer.rs
p2p/src/network/noise/p2p_network_noise_state.rs
p2p/src/network/pnet/p2p_network_pnet_effects.rs
p2p/src/network/scheduler/p2p_network_scheduler_reducer.rs
p2p/src/network/select/p2p_network_select_actions.rs
p2p/src/network/select/p2p_network_select_effects.rs
p2p/src/network/select/p2p_network_select_reducer.rs
p2p/src/network/select/p2p_network_select_state.rs
p2p/src/network/yamux/p2p_network_yamux_effects.rs

Removed optimized handshake, removed optional handshake sending, added proper way to respond to handshake token.

Removed unused code in select protocol

---

p2p/src/network/kad/stream/p2p_network_kad_stream_reducer.rs

This fixes a bug found by p2p-fuzzer in kademlia stream reducer.

p2p/kad: fix buffer index miscalculation

---

p2p/src/service_impl/mio/mod.rs

Limit number of bytes queued for send

Fix vulnerability similar to CVE-2024-32984

---

p2p/tests/connection.rs

Fix for `mutual_rust_to_rust_many` failing

Fix for `mutual_rust_to_rust_many` failing

---

p2p/src/network/identify/p2p_network_identify_protocol.rs
p2p/src/network/kad/p2p_network_kad_internals.rs
p2p/tests/identify.rs

Added bad node  test for identify

Added bad node  test for identify

---

ledger/src/account/account.rs
ledger/src/scan_state/conv.rs
mina-p2p-messages/src/hash_input.rs
mina-p2p-messages/src/string.rs
mina-p2p-messages/src/v2/generated.rs

feat(p2p-messages): Add `ZkappUri` and `TokenSymbol` type with size limit

---

node/common/src/service/rpc/mod.rs

Removed duplicate mod

---

frontend/cypress/e2e/block-production/won-slots/apis.cy.ts
frontend/cypress/e2e/block-production/won-slots/filters.cy.ts
frontend/cypress/e2e/block-production/won-slots/side-panel.cy.ts
frontend/cypress/e2e/block-production/won-slots/table.cy.ts
frontend/src/app/core/services/rust.service.ts
frontend/src/app/core/services/web-node.service.ts
frontend/src/app/features/block-production/won-slots/block-production-won-slots.actions.ts
frontend/src/app/features/block-production/won-slots/block-production-won-slots.component.ts
frontend/src/app/features/block-production/won-slots/block-production-won-slots.effects.ts
frontend/src/app/features/block-production/won-slots/block-production-won-slots.reducer.ts
frontend/src/app/features/block-production/won-slots/block-production-won-slots.service.ts
frontend/src/app/features/block-production/won-slots/block-production-won-slots.state.ts
frontend/src/app/features/block-production/won-slots/filters/block-production-won-slots-filters.component.html
frontend/src/app/features/block-production/won-slots/filters/block-production-won-slots-filters.component.ts
frontend/src/app/features/block-production/won-slots/table/block-production-won-slots-table.component.scss
frontend/src/app/features/dashboard/dashboard.component.ts
frontend/src/app/features/dashboard/dashboard.effects.ts
frontend/src/app/features/dashboard/dashboard.service.ts
frontend/src/app/shared/types/block-production/won-slots/block-production-won-slots-filters.type.ts
frontend/src/environments/environment.ts
frontend/src/index.html

Block production added Discarded key

---

Dockerfile

Fix block production fails in docker container because circuit-blobs are missing in the image

---

Cargo.lock
node/Cargo.toml
node/src/effects.rs
node/src/state.rs
node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_reducer.rs
p2p/src/channels/signaling/mod.rs

Should fix https://discord.com/channels/484437221055922177/1300393986921594940

Transition Frontier Sync: use random peer to fetch staged ledger parts or best tip

---

docker-compose.block-producer.yml
docker-compose.yml

Make external ip configurable in the docker compose setup with `OPENMINA_LIBP2P_EXTERNAL_IP`

feat(docker): Add option to specify the external IP

---

frontend/src/app/features/webnode/web-node-demo-dashboard/web-node-demo-dashboard.component.ts
frontend/src/app/layout/web-node-landing-page/web-node-landing-page.component.html
frontend/src/index.html
frontend/src/styles.scss

Frontend - UI Improvements for the Web Node

---

p2p/src/disconnection/p2p_disconnection_reducer.rs

Added disconnection for all connections for peer, related issue: #368

Added disconnect for all connections

---

frontend/.gitignore
frontend/angular.json
frontend/httpd.conf
frontend/package-lock.json
frontend/package.json

mime type forcing for wasm files
Source map tests

Frontend - Sentry source maps (#903)

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/app.component.html
frontend/src/app/app.component.scss
frontend/src/app/app.component.ts
frontend/src/app/app.module.ts
frontend/src/app/features/block-production/won-slots/block-production-won-slots.actions.ts
frontend/src/app/features/block-production/won-slots/block-production-won-slots.effects.ts
frontend/src/app/features/dashboard/dashboard.module.ts
frontend/src/app/features/webnode/web-node-initialization/web-node-initialization.component.scss
frontend/src/app/layout/block-production-pill/block-production-pill.component.html
frontend/src/app/layout/block-production-pill/block-production-pill.component.scss
frontend/src/app/layout/block-production-pill/block-production-pill.component.ts
frontend/src/app/layout/error-preview/error-preview.component.ts
frontend/src/app/layout/menu-tabs/menu-tabs.component.html
frontend/src/app/layout/menu-tabs/menu-tabs.component.scss
frontend/src/app/layout/menu-tabs/menu-tabs.component.ts
frontend/src/app/layout/menu/menu.component.scss
frontend/src/app/layout/menu/menu.component.ts
frontend/src/app/layout/server-status/server-status.component.html
frontend/src/app/layout/server-status/server-status.component.scss
frontend/src/app/layout/server-status/server-status.component.ts
frontend/src/app/layout/toolbar/toolbar.component.html
frontend/src/app/layout/toolbar/toolbar.component.scss
frontend/src/app/layout/toolbar/toolbar.component.ts
frontend/src/assets/styles/openmina.scss
frontend/src/environments/environment.ts
frontend/src/index.html

Frontend - Block Production Pill

---

node/src/action_kind.rs
node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_actions.rs
node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_reducer.rs
node/src/block_producer_effectful/vrf_evaluator_effectful/block_producer_vrf_evaluator_effectful_actions.rs
node/src/block_producer_effectful/vrf_evaluator_effectful/block_producer_vrf_evaluator_effectful_effects.rs
node/src/rpc/mod.rs
node/src/rpc_effectful/rpc_effectful_effects.rs
node/src/stats/stats_block_producer.rs

Vrf evaluator stats

---

node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_reducer.rs

Eventually it syncs up, but this issue adds a delay to bootstrap.

Fix: Root snarked ledger sync gets stuck

---

node/src/action_kind.rs
p2p/src/network/pubsub/p2p_network_pubsub_actions.rs
p2p/src/network/pubsub/p2p_network_pubsub_reducer.rs
p2p/src/network/pubsub/p2p_network_pubsub_state.rs
p2p/src/network/pubsub/pubsub_effectful/p2p_network_pubsub_effectful_actions.rs
p2p/src/network/pubsub/pubsub_effectful/p2p_network_pubsub_effectful_effects.rs

Organized so that each commit can be reviewed independently to make the review easier.

feat(p2p): More pubsub improvements, docs, cleanup

---

Cargo.lock
Cargo.toml

Includes [openmina/algebra@`d0343f5` (#1)](https://github.com/openmina/algebra/pull/1/commits/d0343f56c517675d2c340d066727d470ce22d552)
To make proof generation faster

Update `algebra` dependency

---

Cargo.lock
Cargo.toml
mina-p2p-messages/src/bigint.rs
node/common/src/service/block_producer/vrf_evaluator.rs
producer-dashboard/src/evaluator/mod.rs
vrf/Cargo.toml
vrf/src/lib.rs
vrf/src/message.rs
vrf/src/output.rs
vrf/src/threshold.rs

For faster vrf evaluation
https://github.com/openmina/num-bigint/commits/on-stack/

Allocate `num-bigint` on the stack

---

vrf/src/output.rs

Bug introduced in https://github.com/openmina/openmina/pull/983

Fix truncating vrf output

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/core/services/web-node.service.ts
frontend/src/app/features/dashboard/dashboard-blocks-sync/dashboard-blocks-sync.component.html
frontend/src/app/features/dashboard/dashboard-blocks-sync/dashboard-blocks-sync.component.scss
frontend/src/app/features/dashboard/dashboard-blocks-sync/dashboard-blocks-sync.component.ts
frontend/src/app/features/dashboard/dashboard-ledger/dashboard-ledger.component.html
frontend/src/app/features/dashboard/dashboard-ledger/dashboard-ledger.component.scss
frontend/src/app/features/dashboard/dashboard-ledger/dashboard-ledger.component.ts
frontend/src/app/features/dashboard/dashboard-network/dashboard-network.component.html
frontend/src/app/features/dashboard/dashboard-network/dashboard-network.component.scss
frontend/src/app/features/web-node/web-node-file-upload/web-node-file-upload.component.html
frontend/src/app/features/web-node/web-node-file-upload/web-node-file-upload.component.scss
frontend/src/app/features/web-node/web-node-file-upload/web-node-file-upload.component.ts
frontend/src/app/features/web-node/web-node-initialization/web-node-initialization.component.ts
frontend/src/app/shared/types/nodes/dashboard/nodes-overview-ledger.type.ts
frontend/src/environments/environment.fuzzing.ts
frontend/src/environments/environment.ts
frontend/src/index.html

Frontend - Added non-BP web node + Dashboard improvements and fixes

---

Cargo.lock
node/src/rpc/heartbeat.rs
node/src/rpc/mod.rs
node/src/rpc_effectful/rpc_effectful_effects.rs

Remove some fields we don't want in the final version and make the values deserializable.

Tweak heartbeat format

---

frontend/package.json
frontend/src/app/core/services/firestore.service.ts
frontend/src/app/features/web-node/web-node-file-upload/web-node-file-upload.component.html
frontend/src/app/features/web-node/web-node-file-upload/web-node-file-upload.component.ts
frontend/src/app/layout/uptime-pill/uptime-pill.component.html
frontend/src/app/layout/uptime-pill/uptime-pill.component.scss
frontend/src/index.html

Frontend - Webnode improvements & bugfixes

---

node/src/block_producer/block_producer_actions.rs

In case of fork, when transition frontier sync commit is pending and we just initiated block production, in case of a specific timing of events, this failure occurred:
> openmina_node_web.js:915 INFO node/src/block_producer/block_producer_actions.rs:17  time = "1738684065418000002";kind = "BlockProducerStagedLedgerDiffCreatePending";       
> openmina_node_web.js:807 panicked at node/src/ledger/write/ledger_write_reducer.rs:123:37:                                                                                                                                             
not yet implemented: handle staged ledger diff creation err: parent staged ledger missing: jwLT4vakRff8bVRRbamkgnYU3tDEMJQXaK7e2Mzd7cj8KmXhozc

Fix Block Producer: missing parent staged ledger for creating new staged ledger diff in case of race condition

---

core/src/block/block_with_hash.rs
node/common/src/service/rpc/mod.rs
node/native/src/graphql/account.rs
node/native/src/graphql/block.rs
node/native/src/graphql/mod.rs
node/src/action_kind.rs
node/src/event_source/event.rs
node/src/event_source/event_source_effects.rs
node/src/rpc/mod.rs
node/src/rpc/rpc_actions.rs
node/src/rpc/rpc_reducer.rs
node/src/rpc_effectful/rpc_effectful_action.rs
node/src/rpc_effectful/rpc_effectful_effects.rs
node/src/rpc_effectful/rpc_service.rs
node/testing/src/service/rpc_service.rs

Added graphql `block` endpoint

Added graphql block endpoint

---

Cargo.lock
Cargo.toml
ledger/src/proofs/transaction.rs
node/common/src/service/block_producer/mod.rs

To debug block proof generation
Requires https://github.com/openmina/algebra/pull/1/commits/150ab8d4cf4918f256580c0d17249ddf11e20aeb and https://github.com/openmina/proof-systems/pull/1/commits/f461b4bf65fe9677f81033ed7c3c4f997caea3fe

Add more debug infos

---

.github/workflows/daily.yaml

feat(ci): Disable openmina daily workflow

---

node/common/src/service/rpc/mod.rs
node/native/src/graphql/mod.rs
node/src/action_kind.rs
node/src/event_source/event.rs
node/src/event_source/event_source_effects.rs
node/src/rpc/mod.rs
node/src/rpc/rpc_actions.rs
node/src/rpc/rpc_reducer.rs
node/src/rpc_effectful/rpc_effectful_action.rs
node/src/rpc_effectful/rpc_effectful_effects.rs
node/src/rpc_effectful/rpc_service.rs
node/testing/src/service/rpc_service.rs

Added graphql genesis block endpoint

Added graphql genesis block endpoint

---

core/src/snark/snark.rs
core/src/snark/snark_job_id.rs
ledger/src/scan_state/scan_state.rs
node/common/src/service/rpc/mod.rs
node/native/src/graphql/mod.rs
node/native/src/graphql/snark.rs
node/src/action_kind.rs
node/src/event_source/event.rs
node/src/event_source/event_source_effects.rs
node/src/rpc/mod.rs
node/src/rpc/rpc_actions.rs
node/src/rpc/rpc_reducer.rs
node/src/rpc_effectful/rpc_effectful_action.rs
node/src/rpc_effectful/rpc_effectful_effects.rs
node/src/rpc_effectful/rpc_service.rs
node/testing/src/service/rpc_service.rs

Added `snarkPool` graphql endpoint
Added `pendingSnarkWork` graphql endpoint

Snark pool graphql routes

---

node/native/src/graphql/mod.rs
node/native/src/graphql/snark.rs

Added 'currentSnarkWorker' graphql endpoint

Added 'currentSnarkWorker' graphql endpoint

---

frontend/package.json
frontend/src/environments/environment.webnodelocal.ts
frontend/src/index.html

Web node local clean-up environment.

Auto open web-node config

---

.github/workflows/changelog.yaml

CI: add a check for checklog changes on PR

---

.github/workflows/ci.yaml
CHANGELOG.md
docker-compose.archive.devnet.compare.yml
node/testing/src/node/ocaml/config.rs
node/testing/src/node/ocaml/mod.rs
node/testing/src/scenarios/multi_node/basic_connectivity_peer_discovery.rs
node/testing/src/scenarios/solo_node/basic_connectivity_accept_incoming.rs

Fix https://github.com/o1-labs/openmina/issues/1158. See https://github.com/MinaProtocol/mina/releases/tag/3.2.0-alpha1

OCaml node dep: update to the latest release

---

.github/workflows/docker.yaml
CHANGELOG.md
Makefile
website/docs/developers/docker-images.md

Fix https://github.com/o1-labs/mina-rust/issues/1336

Docker: push multi platform architecture

---

website/docs/appendix/release-process.mdx
website/docs/developers/scripts/release/merge-back.sh

Website/release: update documentation following first concrete release
