.gitmodules, Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/src/commands/mod.rs, cli/src/commands/snark/mod.rs, cli/src/commands/snark/precalculate_block_verifier_index_and_srs.rs, cli/src/commands/snarker/mod.rs, cli/src/commands/snarker/tracing.rs, cli/src/main.rs, node/lib/Cargo.toml, node/lib/build.rs, node/shared/src/log.rs, snarker/Cargo.toml, snarker/build.rs, snarker/src/account/public_key.rs
=> Tracing console output with proper monotonic time

Cargo.lock, cli/replay_dynamic_effects/Cargo.toml, cli/src/commands/node/mod.rs, cli/src/commands/replay/replay_state_with_input_actions.rs, core/Cargo.toml, core/src/channels.rs, core/src/lib.rs, node/native/src/ext_snark_worker.rs, node/native/src/rpc.rs, node/native/src/service.rs, node/src/lib.rs, node/testing/src/cluster/mod.rs, node/testing/src/cluster/p2p_task_spawner.rs, node/testing/src/service/mod.rs, p2p/Cargo.toml, p2p/src/connection/outgoing/mod.rs, p2p/src/connection/outgoing/p2p_connection_outgoing_effects.rs, p2p/src/identity/peer_id.rs, p2p/src/service_impl/libp2p/behavior.rs, p2p/src/service_impl/libp2p/mod.rs, p2p/src/service_impl/mod.rs, p2p/src/service_impl/webrtc/mod.rs, p2p/src/service_impl/webrtc/native.rs, p2p/src/service_impl/webrtc/web.rs, p2p/src/service_impl/webrtc_with_libp2p.rs
Extract common api and use `web-sys` crate for WebRTC backend in WASM target.
=> P2p Wasm Support

.dockerignore, Dockerfile_FE, README.md, docker-compose.yml
Just a very quick way to launch both the node and the frontend.
Note:
- should instead use a v0.1 tagged version instead of building?
- ~I am trying to have the dockerfile build the frontend with the local environment but somehow it is still showing me the production version, any idea @directcuteo ?~ (fixed, was probably some cache)
=> Add docker compose for demo

.github/workflows/ci.yaml, node/native/src/service.rs, node/src/action_kind.rs, node/src/effects.rs, node/src/p2p/p2p_effects.rs, node/testing/src/cluster/mod.rs, node/testing/src/scenarios/solo_node/bootstrap.rs, node/testing/src/service/mod.rs, p2p/src/connection/p2p_connection_service.rs, p2p/src/service_impl/mod.rs, p2p/src/service_impl/webrtc_with_libp2p.rs
@vlad9486 Instead of having new stubs for P2p-related services when internal libp2p is used, it is better to have an alternative implementation for existing ones, with conditional implementations. These services are used by webrtc logic as well, and as far as I concerned, we want to keep it working, either with external or internal libp2p. Also methods like `outgoing_init` should be defined for any p2p implementation.
Please take a look, probably I can make it even more elegant, like to factor out external libp2p service (discovery related methods).
=> Fix for services in libp2p replacement

node/native/src/block_producer/vrf_evaluator.rs, node/src/block_producer/block_producer_effects.rs, node/src/block_producer/block_producer_state.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_actions.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_effects.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_event.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_reducer.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_service.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_state.rs, node/src/block_producer/vrf_evaluator/mod.rs, node/src/ledger/ledger_service.rs, vrf/src/lib.rs
Addressing the review in #151 
Cleaned up the vrf evaluator code accordingly. 
One last thing that is hanging is moving the logic out of `BlockProducerVrfEvaluatorEvaluationSuccessAction` effects to the enabling condition. I don't really grasp the point made in this [comment](https://github.com/openmina/openmina/pull/151#discussion_r1466140896). Moving the same logic to the enabling condition seems a bit redundant to me as the effect will only dispatch the action with values that makes sense (no input sent for 2 epoch in the future as we have no data for that yet).
I think it could be more elegant if we made the vrf evaluator aware what epoch it's currently evaluating but that would require the overhaul of the evaluator state (later polishing).
=> Vrf evaluator cleanup

node/src/logger/logger_effects.rs, p2p/src/network/scheduler/p2p_network_scheduler_actions.rs, p2p/src/network/select/p2p_network_select_state.rs, p2p/src/network/select/token.rs
We need to see what missing protocol our peer is trying to use.
=> chores(new-libp2p): better error handling

Cargo.lock
Fix compilation on `rustc 1.78.0-nightly (6cc484351 2024-02-10)`
Ran the following commands, to update some dependencies:
```
cargo update -p curve25519-dalek@4.1.1
cargo update -p rand_core@0.5.1
cargo update -p ahash@0.7.7
cargo update -p ahash@0.8.6
```
=> Fix compilation on nightly toolchain

Cargo.lock, mina-p2p-messages/Cargo.toml, mina-p2p-messages/src/core.rs, mina-p2p-messages/src/rpc.rs, mina-p2p-messages/src/rpc_kernel.rs, p2p/src/service_impl/libp2p/mod.rs
- bump version for answer_sync_ledger_query
- sync up with the new Error type
@tizoc Following up our discussion in Slack. Now I assume that the only option is to have a sexp representation for errors. Can you confirm that? Or should we extend that at some point?
=> fix(berkeley-rc1): fix RPCs

Cargo.lock, core/src/block.rs, node/src/ledger/ledger_service.rs, node/src/p2p/p2p_effects.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_reducer.rs, p2p/Cargo.toml, p2p/src/channels/p2p_channels_effects.rs, p2p/src/channels/rpc/p2p_channels_rpc_effects.rs
Use some of the hashing implementation in the `ledger` crate in place of the currently missing hashing code in `mina-p2p-messages`
=> Workaround for missing hashing code in `mina-p2p-messages`

node/src/ledger/ledger_service.rs
Just a fixup that reverts a change introduced in #241 that is not needed anymore after #243 got merged.
=> fixup(ledger_service): Revert hashing modification (not needed after fix in #243)

Cargo.lock, ledger/Cargo.toml, ledger/src/proofs/verifier_index.rs
In this commit I've implemented very basic caching of indices. If that would work fine, we should also include SRS hash to the file name (in case input for verifier index is changed). and probably also move it directly to ledger (unless we don't want to have OS ops in that crate)
=> Cache verifier index

p2p/src/channels/rpc/mod.rs
=> fix(p2p): uncomment back RPC timeouts

ledger/src/proofs/block.rs, ledger/src/proofs/transaction.rs
Use `slots_per_sub_window` instead of `slots_per_window`
+ Add test case
=> Fix block proof generation

mina-p2p-messages/src/v2/manual.rs, vrf/src/output.rs
The previous conversion and serialization fix broke the proof generation due to the prefix and checksum was included in the bytestring.
=> Fix VrfOutput (again)

ledger/src/database/database_impl.rs, ledger/src/tree_version.rs, node/src/action_kind.rs, node/src/ledger/ledger_service.rs, node/src/ledger/mod.rs, node/src/p2p/p2p_effects.rs, node/src/transition_frontier/sync/ledger/snarked/mod.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_actions.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_effects.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_reducer.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_service.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_state.rs, node/src/transition_frontier/sync/ledger/transition_frontier_sync_ledger_state.rs, node/src/transition_frontier/sync/transition_frontier_sync_effects.rs, node/src/transition_frontier/transition_frontier_effects.rs, status.md
- Starts with a `num_accounts` query to fetch the number of accounts in the ledger
- Using the data obtained from the `num_accounts` query results, skip all the empty tree levels and go straight to the first node containing child accounts.
- Uses as a base the previous available ledger (genesis -> staking -> next epoch -> transition frontier root) and queries only the nodes that changed
- Fetches accounts in groups of 64 (up from 2) to lower the amount of queries
- Validations for num accounts, hashes and accounts
=> feat(bootstrap): More efficient snarked ledger synchronization

cli/src/commands/node/mod.rs, node/src/action_kind.rs, node/src/event_source/event.rs, node/src/event_source/event_source_effects.rs, node/src/ledger/ledger_service.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_actions.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_effects.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_reducer.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_service.rs
This is just a temporary workaround until the ledger service has been made fully async.
Changes are:
- New event to notify that the reconstruction is complete
- The ledger ctx structure now stores a copy of the events channel sender.
- Service call to reconstruct the staged ledger doesn't return anything, it spawns a new thread that will perform the computation, and once done it will send the new event to the event channel.
- The reconstructed staged ledger is stored in a temporary place, and the Success action will pick it up and insert it in the staging ledgers map
=> feat(ledger-service): Non blocking version of `staged_ledger_reconstruct`

node/src/action_kind.rs, p2p/src/network/kad/p2p_network_kad_effects.rs, p2p/src/network/kad/p2p_network_kad_reducer.rs, p2p/src/network/kad/p2p_network_kad_state.rs, p2p/src/network/kad/request/p2p_network_kad_request_actions.rs, p2p/src/network/kad/request/p2p_network_kad_request_effects.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_actions.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_effects.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_reducer.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_state.rs, p2p/src/network/p2p_network_effects.rs
Also streams reducer is simplified by splitting stream state into incoming and outgoing ones.
fixes: #315
=> fix(kademlia): prune requests and streams

node/src/transition_frontier/transition_frontier_effects.rs
The initial queries for fetching the accounts were being recorded as queries for fetching hashes.
=> fix(stats): Correctly record sync stats for accounts fetch start

.github/workflows/docker.yaml, docker-compose.dev.yml, docker-compose.yml, frontend/Dockerfile, frontend/angular.json, frontend/nginx.compose.conf, frontend/src/environments/environment.compose.ts
- separate FE environment for compose
- nginx reverse proxy for node
- compose with default network
- FE image build with GHA
- tags for docker images
=> Use Docker Hub images in docker compose

Cargo.lock, cli/src/commands/node/mod.rs, node/Cargo.toml, node/src/account/secret_key.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_effects.rs, node/src/transition_frontier/transition_frontier_state.rs
Adds a config option `--producer-key <sk>` to enable the block producer in a non-test run
Also including a small fix for the VRF evaluator initialisation.
=> Add config option to enable block producer + small fix for VRF evaluator

CHANGELOG.md, node/src/transition_frontier/sync/ledger/mod.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_actions.rs
=> fix(transition-frontier): Ensure that by the time the staged ledger reconstruct is complete, the target has not changed

Cargo.lock, cli/src/commands/node/mod.rs, cli/src/commands/replay/replay_state_with_input_actions.rs, node/Cargo.toml, node/native/Cargo.toml, node/native/src/service.rs, node/src/block_producer/block_producer_service.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_service.rs, node/src/ledger/ledger_manager.rs, node/src/ledger/ledger_service.rs, node/src/ledger/mod.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_service.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_service.rs, node/src/transition_frontier/transition_frontier_service.rs, node/testing/src/cluster/mod.rs, node/testing/src/scenarios/cluster_runner.rs, node/testing/src/service/mod.rs
This PR adds `ledger_manager` module, which defines `LedgerManager`, a service which launches a thread keeping track of a `LedgetCtx` and handling requests querying its state and making changes. All operations are performed asyncronously in a thread separate from the caller's, but syncronous wrappers for these calls are provided to avoid dramatic changes to ledger service API yet.
This new service is created along with `NodeService` instance and the latter has a handle on the former, so it can redirect incoming requests to the new service. This way we avoid big changes to `NodeService`'s API at this point. Once this is merged, we can consider updating call sites to asynchronous workflow on case-by-case basis.
=> Create a separate service to manage a LedgerCtx in separate thread.

p2p/src/network/kad/stream/p2p_network_kad_stream_effects.rs, p2p/testing/src/event.rs, p2p/testing/src/predicates.rs, p2p/tests/kademlia.rs
I have code to handle action being `SendResponse` and state being `Incoming(RequestIsReady)` in kademlia stream effects, this allows for node to respond to incoming requests.
@akoptelov, Could you take a look
=> Bugfix for #361

node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_actions.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_effects.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_reducer.rs
In some cases `Success` was being dispatched directly without going through `MerkleTreeSyncSuccess` first.
=>  Fix order of successful snarked ledger sync actions and enabling conditions

CHANGELOG.md, node/src/ledger/ledger_service.rs
This used to fail before because the `supercharged_coinbase_factor` value in the constants used to be `2`, but now that the correct value `1` is used the issue is solved.
re: #386
=> fix(ledger-service) Use `supercharge_coinbase` value from the block

mina-p2p-messages/src/v2/manual.rs
This was causing the genesis protocol state hash to be computed incorrectly.
=> fix(node): Fix zero value for the empty coinbase stack data hash

core/src/block/genesis.rs, mina-p2p-messages/src/v2/manual.rs
As suggested in https://github.com/openmina/openmina/pull/390#pullrequestreview-2048600830
=> tweak: Rename `zero` methods to `empty`

Cargo.lock, Cargo.toml, core/src/block/block_with_hash.rs, ledger/Cargo.toml, ledger/src/proofs/caching.rs, node/Cargo.toml, node/account/Cargo.toml, node/invariants/src/transition_frontier/only_syncs_to_better_blocks.rs, node/native/src/service.rs, node/src/ledger/ledger_manager.rs, node/src/ledger/ledger_service.rs, node/src/recorder/mod.rs, node/testing/Cargo.toml, snark/Cargo.toml
- Replaced bincode with cbor as bincode has [this known issue](https://github.com/bincode-org/bincode/issues/548) which affected us.
- Replaced non-deterministic `getrandom` calls in p2p service with a deterministic one. @vlad9486 this breaks debugger compatibility as you know.
- Fixed race condition causing non-determinism during replay. Race condition was caused by the way we reconstructed ledger in another thread and the way we notified the response.
closes: https://github.com/openmina/mina-issues/issues/52
=> Fix record/replay

.github/workflows/lint.yml, Cargo.lock, cli/src/commands/snark/precalculate_block_verifier_index_and_srs.rs, ledger/Cargo.toml, ledger/src/proofs/caching.rs, ledger/src/proofs/verifier_index.rs, node/testing/src/scenarios/p2p/basic_connection_handling.rs
Also added a `cargo check`  lint step that will fail if there are warnings.
=> fix(ledger): propagate verifier index serde errors

Cargo.lock, ledger/Cargo.toml, ledger/src/proofs/caching.rs, node/Cargo.toml, node/src/recorder/mod.rs, node/testing/Cargo.toml, node/testing/src/cluster/mod.rs
serde_cbor is unmaintained while ciborium is actively maintained. Also serde_cbor may be negativelly affecting our build times.
=> chore(node): Replace serde_cbor with ciborium

Cargo.lock
Fixes https://github.com/openmina/openmina/security/dependabot/27
=> fix: Update rustls dependency

cli/src/commands/node/mod.rs
Currently effect is that no default peers are added.
=> fix(cli): introduce --seed option

Cargo.lock, Cargo.toml, node/Cargo.toml, node/src/action.rs, node/src/watched_accounts/watched_accounts_actions.rs, node/src/watched_accounts/watched_accounts_reducer.rs
Added limit size for [`Action`](https://github.com/openmina/openmina/blob/develop/node/src/action.rs#L23), if size of `Action` is bigger than `512` bytes code won't compile with error:
```
attempt to compute `0_usize - 1_usize`, which would overflow
```
=> Added compile time check for size limit of Action

Cargo.lock, ledger/src/proofs/caching.rs, ledger/src/proofs/verifier_index.rs, node/Cargo.toml, node/src/daemon_json/json_ledger.rs, node/src/daemon_json/mod.rs, node/src/transition_frontier/genesis/transition_frontier_genesis_config.rs
When genesis config is loaded and genesis ledger reconstructed from JSON config, it is also cached on disk. When the same JSON loaded again, the node finds the cache on disk and loads it instead, which is significantly faster than building the ledgers from JSON.
=> Implement genesis config caching.

fuzzer/src/lib.rs, p2p/src/fuzzer.rs, p2p/src/network/identify/stream/p2p_network_identify_stream_effects.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_effects.rs, p2p/src/network/pubsub/p2p_network_pubsub_effects.rs, p2p/src/network/rpc/p2p_network_rpc_effects.rs, p2p/src/network/yamux/p2p_network_yamux_effects.rs
Some time ago @akoptelov suggested to extend the p2p-fuzzer to flip the `FIN` flag of *yamux* packets.
Following this suggestion, this patch to produces random mutations to any of the `YamuxFlags`.
=> p2p-fuzzer: optionally fuzz YamuxFlags when sending packets

node/common/src/service/service.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_actions.rs, node/src/transition_frontier/genesis/transition_frontier_genesis_config.rs
Got an empty block: https://devnet.minaexplorer.com/wallet/B62qpdPtz7QSTcPLkDuSdGGv6VkdhG5Gy2NLFBLfkyfR6K3KSfviW4Y/blocks
Still need to test some of the changes
=> Fix (empty) block production on devnet

fuzzer/src/lib.rs, p2p/src/fuzzer.rs, p2p/src/network/scheduler/p2p_network_scheduler_actions.rs
Fixes for bugs hit while running the p2p fuzzer against the OCaml fuzzer. Surprisingly the bugs found so far are in the Rust implementation, including the fuzzer itself.
- Fixes issues when handling ranges in fuzzer/mutators.
- Fixes enabling condition that filtered PruneStreams actions when the peer is in error state.
=> P2p fuzz fixes

p2p/src/network/select/p2p_network_select_effects.rs
Fixes #543, added `Token::Handshake` in data sent when negotiating multiplexing protocol.
If handshake is not sent with multiplexing protocol during negoation with OCaml node, OCaml node throws error when trying to dial rust node in [`go-multistream@v0.3.3/client.go`](https://github.com/multiformats/go-multistream/blob/master/client.go):
```
func readMultistreamHeader(r io.Reader) error {
tok, err := ReadNextToken(r)
if err != nil {
return err
}
if tok != ProtocolID {
return errors.New("received mismatch in protocol id")
}
return nil
}
```
With error: `received mismatch in protocol id`
=> Added handshake in data sent during multiplex negotiation

node/src/consensus/consensus_actions.rs, node/src/consensus/consensus_reducer.rs, node/src/logger/logger_effects.rs
Note: initially used to debug an issue on CI where the scenario tests would fail when `display(hash)` was used for consensus actions.
=> tweak: More consensus logging

node/testing/src/node/ocaml/mod.rs, p2p/src/network/kad/p2p_network_kad_actions.rs, p2p/src/network/kad/p2p_network_kad_internals.rs, p2p/src/network/kad/p2p_network_kad_protocol.rs, p2p/src/network/kad/request/p2p_network_kad_request_reducer.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_effects.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_state.rs
Added CID for kademlia find node request, to better support OCaml node.
Removed different implementation of `P2pNetworkKadKey` for `PeerId` and `&PeerId`
```rs
impl From<PeerId> for P2pNetworkKadKey {
fn from(value: PeerId) -> Self {
let digest = Sha256::digest(value.to_bytes());
P2pNetworkKadKey(<U256 as ArrayEncoding>::from_be_byte_array(digest))
}
}
impl From<&PeerId> for P2pNetworkKadKey {
fn from(value: &PeerId) -> Self {
P2pNetworkKadKey(U256::from_be_byte_array(Sha256::digest(
libp2p_identity::PeerId::from(*value).to_bytes(),
)))
}
}
```
This would generate different `P2pNetworkKadKey`:
```
[p2p/src/network/kad/p2p_network_kad_internals.rs:585:9] peer_id = PeerId(2bEgBrPTzL8wov2D4Kz34WVLCxR4uCarsBmHYXWKQA5wvBQzd9H)
[p2p/src/network/kad/p2p_network_kad_internals.rs:586:9] …
```
=> Added CID in kademlia find node request

p2p/src/network/kad/p2p_network_kad_effects.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_reducer.rs, p2p/src/network/p2p_network_reducer.rs, p2p/src/peer/p2p_peer_actions.rs, p2p/testing/src/cluster.rs, p2p/testing/src/event.rs, p2p/testing/src/lib.rs, p2p/testing/src/redux.rs, p2p/testing/src/rust_node.rs, p2p/tests/kademlia.rs
Added condition for `P2pPeerAction::Discovered` to not allow for self discovery and added test with "bad" node.
=> Added test to prevent self connection on kademlia

node/src/block_producer/block_producer_effects.rs, node/src/effects.rs, node/src/ledger/ledger_effects.rs, node/src/ledger/write/ledger_write_actions.rs, node/src/ledger/write/ledger_write_reducer.rs, node/src/p2p/p2p_effects.rs, node/src/snark_pool/candidate/snark_pool_candidate_reducer.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_reducer.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_reducer.rs, node/src/transition_frontier/sync/transition_frontier_sync_effects.rs, p2p/src/channels/rpc/p2p_channels_rpc_actions.rs, p2p/src/channels/rpc/p2p_channels_rpc_effects.rs, p2p/src/channels/streaming_rpc/p2p_channels_streaming_rpc_actions.rs, p2p/src/channels/streaming_rpc/p2p_channels_streaming_rpc_effects.rs, p2p/src/discovery/p2p_discovery_effects.rs, p2p/tests/rpc.rs
Improvements related to #588
Doesn't handle cases where some other action is dispatched if the current one is interrupted by the enabling condition.
=> Replace conditional dispatching with callbacks.

node/src/block_producer/block_producer_effects.rs, node/src/consensus/consensus_reducer.rs, node/src/ledger/ledger_manager.rs, node/src/ledger/ledger_service.rs, node/src/transition_frontier/sync/ledger/snarked/transition_frontier_sync_ledger_snarked_service.rs, node/src/transition_frontier/sync/transition_frontier_sync_actions.rs, node/src/transition_frontier/sync/transition_frontier_sync_effects.rs, node/src/transition_frontier/sync/transition_frontier_sync_reducer.rs
=> feat(transition_frontier): Reuse the previous root snarked ledger on sync

mina-p2p-messages/src/string.rs
Get rid of some redundancy introduced in #632
=> feat(mina-p2p-messages): Combine implementations of bounded strings

cli/src/commands/misc.rs, core/src/log.rs, node/src/p2p/p2p_effects.rs, node/src/rpc/mod.rs, node/src/rpc/rpc_effects.rs, node/testing/src/node/ocaml/mod.rs, node/testing/src/scenarios/multi_node/basic_connectivity_initial_joining.rs, node/testing/src/scenarios/multi_node/connection_discovery.rs, node/testing/src/scenarios/solo_node/basic_connectivity_accept_incoming.rs, node/testing/src/scenarios/solo_node/basic_connectivity_initial_joining.rs, p2p/src/connection/outgoing/mod.rs, p2p/src/identity/peer_id.rs, p2p/src/network/identify/stream/p2p_network_identify_stream_effects.rs, p2p/src/network/identify/stream/p2p_network_identify_stream_reducer.rs, p2p/src/network/kad/bootstrap/p2p_network_kad_bootstrap_state.rs, p2p/src/network/kad/p2p_network_kad_internals.rs, p2p/src/network/kad/p2p_network_kad_protocol.rs, p2p/src/network/kad/p2p_network_kad_reducer.rs, p2p/src/network/kad/request/p2p_network_kad_request_effects.rs, p2p/src/network/kad/request/p2p_network_kad_request_reducer.rs, p2p/src/network/kad/stream/p2p_network_kad_stream_reducer.rs, p2p/src/network/p2p_network_state.rs, p2p/src/network/pubsub/p2p_network_pubsub_reducer.rs, p2p/src/network/select/p2p_network_select_effects.rs, p2p/src/p2p_effects.rs, p2p/testing/src/cluster.rs, p2p/testing/src/libp2p_node.rs, p2p/testing/src/predicates.rs, p2p/testing/src/test_node.rs, p2p/tests/identify.rs
This is a WIP with the purpose of removing code that can panic/crash the node.
This PR:
- Adds `bug_condition!()`: we can use it to log errors that should never happen in runtime. We can still set `PANIC_ON_BUG=true` to force a panic.
- Replaces `From` implementations that were fallible (they shouldn't) by a `TryForm` version. Most P2P code is affected by this change because of conversions between our `PeerID` type and the one used by libp2p. This propagates upwards to most conversions.
=> Replace fallible from implementations by try_from version

Dockerfile, ledger/src/proofs/gates.rs
Also added `OPENMINA_CIRCUIT_BLOBS_BASE_DIR` and a default search path `/usr/local/lib/openmina/circuit-blobs`
=> fix: Put circuit blobs in the right place when building docker images

ledger/src/scan_state/transaction_logic.rs
Needs to be this way so that we can verify the VK update against the old VK
=> fix(ledger): Only update VK cache after handling the VK update itself

node/src/ledger/ledger_manager.rs, node/src/ledger/ledger_service.rs
Should only include the producer if it delegates to itself.
=> fix(block-producer): Fix delegator table construction 

core/src/block/block_with_hash.rs, mina-p2p-messages/src/v2/generated.rs, node/src/ledger/ledger_effects.rs, node/src/ledger/ledger_manager.rs, node/src/ledger/ledger_service.rs, node/src/ledger/read/mod.rs, node/src/rpc/rpc_effects.rs, node/src/rpc/rpc_state.rs, node/src/transition_frontier/genesis/mod.rs, node/src/transition_frontier/sync/transition_frontier_sync_actions.rs, node/src/transition_frontier/sync/transition_frontier_sync_effects.rs, node/src/transition_frontier/sync/transition_frontier_sync_state.rs, node/src/transition_frontier/transition_frontier_effects.rs, node/testing/src/cluster/runner/mod.rs
This removes fetching a `StagedLedger` by its merkle root hash: multiple `StagedLedger` can have the same merkle root hash
Alternative to #705
=> Handle multiple `StagedLedger` having the same merkle root hash

node/src/block_producer/block_producer_effects.rs, node/src/ledger/ledger_manager.rs, node/src/ledger/ledger_service.rs, node/src/ledger/write/mod.rs
If the epoch of the block being producer is greater than the epoch of the parent block, then the next epoch ledger must be used.
=> fix(block-producer): Use the correct staking ledger after epoch boundaries

core/src/block/block_with_hash.rs, node/src/action_kind.rs, node/src/block_producer/block_producer_effects.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_actions.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_effects.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_reducer.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_state.rs, p2p/src/peer/p2p_peer_actions.rs
We don't need to keep track of the last heigh of the previous epoch. If the epoch of the best tip and the block at the root of the transition frontier match, we know that the snarked ledger at the root belongs to a block that has been finalized already because there are 290 blocks between it and the best tip.
=> fix(vrf-evaluator) Improve readiness check logic

frontend/httpd.conf, frontend/src/app/features/benchmarks/wallets/benchmarks-wallets.reducer.ts, frontend/src/app/features/benchmarks/wallets/benchmarks-wallets.service.ts, frontend/src/app/features/block-production/overview/slot-details/block-production-overview-slot-details.component.ts, frontend/src/app/features/block-production/won-slots/side-panel/block-production-won-slots-side-panel.component.ts, frontend/src/assets/environments/staging.js, frontend/src/environments/environment.ts
- Add CORS headers
- Fix error on mina network
=> Frontend - CORS Headers in Apache

node/src/event_source/event_source_effects.rs, node/src/rpc/rpc_effects.rs, node/testing/src/scenarios/driver.rs, p2p/Cargo.toml, p2p/src/connection/outgoing/mod.rs, p2p/src/disconnection/p2p_disconnection_reducer.rs, p2p/src/network/kad/request/p2p_network_kad_request_reducer.rs, p2p/src/network/noise/p2p_network_noise_reducer.rs, p2p/src/network/pubsub/p2p_network_pubsub_reducer.rs, p2p/src/network/pubsub/pubsub_effectful/p2p_network_pubsub_effectful_effects.rs, p2p/src/network/scheduler/p2p_network_scheduler_actions.rs, p2p/src/network/scheduler/p2p_network_scheduler_reducer.rs, p2p/src/network/yamux/p2p_network_yamux_reducer.rs, p2p/src/p2p_config.rs, p2p/src/p2p_event.rs, p2p/src/p2p_state.rs, p2p/src/service_impl/mio/mod.rs, p2p/testing/src/redux.rs
Delay removal of the connection from the network state machine until the disconnection actually occurs at the TCP level.
=> Keep state consistent during disconnection

ledger/src/proofs/step.rs, ledger/src/proofs/transaction.rs, ledger/src/proofs/util.rs, ledger/src/proofs/verification.rs
The bug was introduced in #721
Restore `proof_evaluation_to_absorption_sequence`, because it's actually different than `proof_evaluation_to_list`
=> Fix zkapp verification with feature flags

ledger/src/proofs/accumulator_check.rs, ledger/src/proofs/verification.rs, ledger/src/staged_ledger/staged_ledger.rs
Doesn't enable verifications during block application yet (that will come with the changes to the catchup process, so that blocks are queued for verification before applying).
=> feat(proofs): Batch verification of completed works in blocks

.github/workflows/ci.yaml
To avoid this issue (which I assume is caused by us caching results from run to run):
```
it looks like the Rust project used to create this Wasm file was linked against
version of wasm-bindgen that uses a different bindgen format than this binary:
rust Wasm file schema version: 0.2.93
this binary schema version: 0.2.94
```
=> fix(ci): Install a specific version of wasm-bindgen-cli

Cargo.lock, Cargo.toml
When browser tab sleeps, performance::now() doesn't tick, causing this issue.
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#ticking_during_sleep
=> Fix WebNode: initial_time + Instant::now() != current time

p2p/src/network/pubsub/p2p_network_pubsub_reducer.rs, p2p/src/network/pubsub/p2p_network_pubsub_state.rs
Added limit for IWANT requests
=> Added limit for IWANT requests

frontend/src/app/features/block-production/won-slots/cards/block-production-won-slots-cards.component.ts
Currently, this stat doesn't show the progress of the current epoch. This fix displays the percentage of the current epoch completed.
=> Correcting epoch progress

ledger/src/base.rs, ledger/src/database/database.rs, ledger/src/database/database_impl.rs, ledger/src/mask/mask.rs, ledger/src/mask/mask_impl.rs
2 commits:
1 -  Fix map `token_to_accounts` in Mask
The map must contain the `TokenId` derived from the `AccountId`
Rename to `token_owners`
All tests passed after this commit: https://github.com/openmina/openmina/actions/runs/11520393012
2  - Remove map `token_owners`:
Because it's expensive (because of `AccountId::derive_token_id`)
and it's not used anywhere in the node
=> Fix map `token_to_accounts` in Mask

ledger/src/scan_state/transaction_logic.rs
Ensure that we construct results in the same order as the OCaml implementation, and that the order of evaluation also remains compatible with the OCaml version (right-to-left).
=> fix(ledger): Fix handling of precondition checks ordering

Dockerfile, docker-compose.block-producer.yml, docker-compose.dev.yml, docker-compose.yml
Exposing the p2p ports in the compose files so that they are visible from the outside.
=> fix: Expose p2p port in docker

node/src/block_producer/block_producer_actions.rs, node/src/block_producer/block_producer_state.rs, node/src/consensus/consensus_actions.rs, node/src/snark_pool/candidate/snark_pool_candidate_actions.rs, node/src/snark_pool/snark_pool_actions.rs, node/src/snark_pool/snark_pool_state.rs
Start producing block earlier, especially for the webnode where proof generation is slower for now.
=> Block Producer: start production earlier

.idea/vcs.xml, core/src/consensus.rs
Panic with message: `Subtract with overflow`
at core/src/consensus.rs:78:27
When debug vars:
max_slot: 98879
global_slot + 1: 98880
=> fix subtract with overflow in relative_min_window_density() consensus.rs

cli/src/commands/node/mod.rs, core/src/thread.rs, frontend/docker/startup.sh, ledger/src/proofs/circuit_blobs.rs, ledger/src/proofs/provers.rs, ledger/src/proofs/verifiers.rs, node/common/src/service/block_producer/mod.rs, node/common/src/service/builder.rs, node/native/src/node/builder.rs, node/native/src/service/builder.rs, node/src/block_producer/block_producer_actions.rs, node/src/p2p/callbacks/p2p_callbacks_reducer.rs, node/src/state.rs, node/src/transition_frontier/genesis/transition_frontier_genesis_config.rs, node/testing/src/cluster/mod.rs, node/web/src/lib.rs, node/web/src/node/builder.rs, p2p/src/disconnection/p2p_disconnection_actions.rs
Affects both, WebNode and Native node startup times.
=> Block producer: speed up startup by calculating provers index in parallel with bootstrap

core/src/consensus.rs, node/src/rpc/mod.rs, node/src/rpc_effectful/rpc_effectful_effects.rs, node/src/transition_frontier/sync/ledger/staged/transition_frontier_sync_ledger_staged_state.rs, p2p/src/channels/streaming_rpc/p2p_channels_streaming_rpc_state.rs, p2p/src/channels/streaming_rpc/rpcs/staged_ledger_parts.rs
=> Rpc Root Staged Ledger Sync: expose parts fetch progress

node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_reducer.rs, node/src/ledger/ledger_effects.rs
This happens with producer accounts that are too new and haven't made it to the staking ledger yet.
=> fix(vrf-evaluator): Handle cases where the delegator table is empty

frontend/httpd.conf, frontend/src/app/features/block-production/won-slots/block-production-won-slots.effects.ts, frontend/src/app/features/block-production/won-slots/block-production-won-slots.reducer.ts, frontend/src/app/features/block-production/won-slots/side-panel/block-production-won-slots-side-panel.component.ts, frontend/src/app/features/webnode/web-node-not-supported/web-node-not-supported.component.html, frontend/src/app/features/webnode/web-node-not-supported/web-node-not-supported.component.scss, frontend/src/app/features/webnode/web-node-not-supported/web-node-not-supported.component.ts, frontend/src/app/features/webnode/webnode.component.ts, frontend/src/app/shared/helpers/webnode.helper.ts
mime type forcing for wasm files
=> Frontend - Change mime type for wasm

frontend/.gitignore, frontend/angular.json, frontend/httpd.conf, frontend/package-lock.json, frontend/package.json
mime type forcing for wasm files
Source map tests
Frontend - Javascript Mime Type
=> Frontend - Sentry source maps (#904)

node/src/rpc_effectful/rpc_effectful_effects.rs
Return the actual next won slot, not the first won slot we have.
=> fix(rpc): Fix `next_won_slot`

node/src/rpc/mod.rs, node/src/rpc_effectful/rpc_effectful_effects.rs
Using the data from the stats instead.
=> fix(rpc): Replace `next_won_slot` in `/status` with `current_block_production_attempt`

node/src/block_producer/block_producer_reducer.rs, node/src/stats/stats_block_producer.rs, node/src/transition_frontier/sync/transition_frontier_sync_effects.rs
Also add `bug_condition!` calls in the block producer.
=> fix(transition-frontier): Skip verification of completed works in locally produced blocks

ledger/src/proofs/public_input/plonk_checks.rs
Initially, it was used to reflect the OCaml code in `src/lib/pickles/plonk_checks`. However, I do think we have to change that as it makes the code more readable from a cryptography point of view.
=> Ledger: use eval pt name instead of fst and snd

cli/replay_dynamic_effects/src/lib.rs, core/src/invariants.rs, node/common/src/service/service.rs, node/invariants/src/invariant_result.rs, node/invariants/src/lib.rs, node/testing/src/cluster/mod.rs, node/testing/src/service/mod.rs, p2p/src/channels/snark/p2p_channels_snark_actions.rs
With protocol built on top of WebRTC, nodes should be able to have their snark pools in sync with each other, but that wasn't a case because of the bug fixed by this pr.
=> Fix WebRTC: snark pool propagation

mina-p2p-messages/src/v2/manual.rs, node/src/action_kind.rs, node/src/consensus/consensus_actions.rs, node/src/consensus/consensus_reducer.rs, node/src/consensus/consensus_state.rs, node/src/p2p/peer/p2p_peer_actions.rs, node/src/state.rs, node/testing/src/scenarios/solo_node/bootstrap.rs
@tizoc Please review this commit  once you have some time: https://github.com/openmina/openmina/pull/878/commits/23e0d35fdeea7d08d6cc21710aba0204dafd2151
=> feat(consensus): Implement block pre-validation

node/src/consensus/consensus_reducer.rs, node/src/state.rs
Accept blocks that have a global slot higher than our best tip in case we are out of sync. We cannot currently differentiate between gossip blocks and requested blocks when using the WebRTC transport, so in the meantime lets use this other heuristic instead.
=> feat(consensus): More permissive block receipt time check

ledger/src/account/account.rs, ledger/src/proofs/to_field_elements.rs
This reduces time to compute the merkle root hash of the full ledger (devnet) from 11 seconds to 6 seconds.
=> Cache default zkapp hash

.drone.yml, .github/workflows/ci.yaml, Dockerfile, README.md, docker/producer-dashboard/Dockerfile, node/testing/docker/Dockerfile.openmina, node/testing/docker/Dockerfile.test, run.yaml, tools/bootstrap-sandbox/Dockerfile
We need https://github.com/rust-lang/rust/pull/129195 for https://github.com/openmina/openmina/pull/939:
[openmina/algebra@`6c74e96` (#1)](https://github.com/openmina/algebra/pull/1/commits/6c74e96e3808b63790b9668f1d9b130b46114c80)
=> Change minimum Rust toolchain to 1.83

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, core/Cargo.toml, ledger/Cargo.toml, ledger/src/account/account.rs, ledger/src/port_ocaml/hash.rs, ledger/src/proofs/block.rs, ledger/src/proofs/group_map.rs, ledger/src/proofs/numbers/currency.rs, ledger/src/proofs/public_input/messages.rs, ledger/src/proofs/public_input/scalar_challenge.rs, ledger/src/proofs/step.rs, ledger/src/proofs/transaction.rs, ledger/src/proofs/util.rs, ledger/src/proofs/wrap.rs, ledger/src/proofs/zkapp.rs, ledger/src/scan_state/currency.rs, ledger/src/scan_state/fee_excess.rs, ledger/src/scan_state/transaction_logic.rs, mina-p2p-messages/Cargo.toml, mina-p2p-messages/src/bigint.rs, node/Cargo.toml, node/common/Cargo.toml, poseidon/Cargo.toml, poseidon/src/hash.rs, poseidon/src/lib.rs, snark/Cargo.toml, tools/fuzzing/Cargo.toml, vrf/Cargo.toml
Related PR:
- https://github.com/openmina/proof-systems/pull/1
- https://github.com/openmina/algebra/pull/1
=> Use faster field implementation in `wasm` target

node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_actions.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_reducer.rs
The best tip's epoch number was passed to the stats. This caused the wrong counter to increment resulting in more evaluated slots for the current_epoch than max_slots
=> Fix epoch number in BeginEpochEvaluation action

frontend/package-lock.json, frontend/package.json, frontend/src/app/core/helpers/file-progress.helper.ts, frontend/src/app/core/services/rust.service.ts, frontend/src/app/core/services/sentry.service.ts, frontend/src/app/features/benchmarks/wallets/benchmarks-wallets.component.html, frontend/src/app/features/benchmarks/wallets/benchmarks-wallets.effects.ts, frontend/src/app/features/block-production/won-slots/block-production-won-slots.component.html, frontend/src/app/features/block-production/won-slots/block-production-won-slots.component.ts, frontend/src/app/features/block-production/won-slots/block-production-won-slots.service.ts, frontend/src/app/features/dashboard/dashboard-blocks-sync/dashboard-blocks-sync.component.ts, frontend/src/app/features/dashboard/dashboard-ledger/dashboard-ledger.component.ts, frontend/src/app/features/dashboard/dashboard.component.ts, frontend/src/app/features/mempool/mempool.service.ts, frontend/src/app/layout/parse-files/parse-files.component.html, frontend/src/app/layout/parse-files/parse-files.component.ts, frontend/src/app/layout/server-status/server-status.component.html, frontend/src/app/layout/server-status/server-status.component.scss, frontend/src/app/layout/web-node-landing-page/web-node-landing-page.component.html, frontend/src/app/layout/web-node-landing-page/web-node-landing-page.component.ts, frontend/src/app/shared/helpers/date.helper.ts, frontend/src/environments/environment.ts, frontend/src/index.html
Parse file example
benchmarks fix
=> Frontend - Sentry sync events & transactions fix model

CHANGELOG.md, node/src/external_snark_worker/external_snark_worker_reducer.rs, node/src/snark_pool/candidate/snark_pool_candidate_reducer.rs, node/src/snark_pool/snark_pool_actions.rs, node/src/snark_pool/snark_pool_reducer.rs, node/src/transaction_pool/transaction_pool_actions.rs, node/src/transaction_pool/transaction_pool_reducer.rs
libp2p layer takes care of the rest
=> fix(mempool): Only rebroadcast locally injected transactions

Cargo.lock, cli/src/commands/node/mod.rs, core/Cargo.toml, core/src/lib.rs, node/native/src/node/builder.rs, node/src/action_kind.rs, node/src/state.rs, p2p/src/disconnection/mod.rs, p2p/src/disconnection/p2p_disconnection_actions.rs, p2p/src/disconnection/p2p_disconnection_reducer.rs, p2p/src/p2p_config.rs, p2p/src/p2p_reducer.rs, p2p/src/p2p_state.rs
=> Better seed node

node/src/reducer.rs
This error message was missing context.
=> fix: Better logging of p2p action errors

.github/workflows/ci.yaml, Cargo.lock, core/Cargo.toml, node/common/Cargo.toml, node/common/src/service/block_producer/mod.rs, node/common/src/service/builder.rs, node/common/src/service/rpc/stats.rs, node/common/src/service/service.rs, node/common/src/service/snarks.rs, p2p/Cargo.toml
By dynamic threads I mean threads that are spawned after the initial startup of the node. After this change, number of threads will stay constant for the node.
fixes: #991
=> Fix: get rid of dynamic threads

node/common/src/service/block_producer/vrf_evaluator.rs
We may end up stealing resources from other parts of the system that are of higher priority. But even more important, the parallel version is non-deterministic and may return different delegators each time.
=> fix(vrf): Don't use parallelism when computing won slots

core/src/log.rs, ledger/src/proofs/zkapp.rs, ledger/src/zkapps/intefaces.rs
Corrected `prefferable` to `preferable`
Corrected `responsability` to `responsibility`
Corrected `ressource` to `resource`
=> fix: typos in documentation files

p2p/src/network/yamux/p2p_network_yamux_reducer.rs
Added temporary fix in yamux so that rust node is able to sync from rust node, in this PR proper handling of outgoing data with respect to window size is removed
=> Added temporary fix for data handling in yamux

p2p/src/network/yamux/p2p_network_yamux_actions.rs, p2p/src/network/yamux/p2p_network_yamux_reducer.rs, p2p/src/network/yamux/p2p_network_yamux_state.rs
* Removed frame cloning in `P2pNetworkYamuxAction::IncomingFrame`
* Changed types in `YamuxFrameInner` from `i32` to `u32`
=> Minor refactors in yamux layer

ledger/src/proofs/transaction.rs, ledger/src/transaction_pool.rs
Apply changes from MinaProtocol/mina#16401
=> Fix transaction pool `revalidate`

p2p/src/network/yamux/p2p_network_yamux_reducer.rs, p2p/src/service_impl/mio/mod.rs
Refactor window size update to use `saturating_sub` instead of `wrapping_sub`
=> Refactor window size update to prevent underflow in stream

node/common/src/service/rpc/mod.rs, node/src/action.rs, node/src/action_kind.rs, node/src/consensus/mod.rs, node/src/effects.rs, node/src/lib.rs, node/src/logger/logger_effects.rs, node/src/p2p/callbacks/p2p_callbacks_reducer.rs, node/src/reducer.rs, node/src/state.rs, node/src/transition_frontier/candidate/mod.rs, node/src/transition_frontier/candidate/transition_frontier_candidate_actions.rs, node/src/transition_frontier/candidate/transition_frontier_candidate_reducer.rs, node/src/transition_frontier/candidate/transition_frontier_candidate_state.rs, node/src/transition_frontier/mod.rs, node/src/transition_frontier/sync/transition_frontier_sync_actions.rs, node/src/transition_frontier/transition_frontier_actions.rs, node/src/transition_frontier/transition_frontier_effects.rs, node/src/transition_frontier/transition_frontier_reducer.rs, node/src/transition_frontier/transition_frontier_state.rs, node/src/watched_accounts/watched_accounts_actions.rs
Since it no longer is just about consensus logic, making this change.
re: #998
=> Refactor: Transfer consensus state machine as transition frontier candidates state machine

node/src/action_kind.rs, node/src/block_producer/block_producer_reducer.rs, node/src/block_producer_effectful/block_producer_effectful_actions.rs, node/src/block_producer_effectful/block_producer_effectful_effects.rs
Produced blocks do not always get injected to the transition frontier
=> feat(heartbeats): Track produced blocks earlier

tools/heartbeats-processor/.sqlx/query-45341663b6eb18a14a7106b3bf53a63c585f507ac1a957ee60a89b0de50fc9fc.json, tools/heartbeats-processor/src/local_db.rs, tools/heartbeats-processor/src/main.rs, tools/heartbeats-processor/src/remote_db.rs
- More reporting
- Use the window start as the lower bound for queries when the local database is first instantiated
- Process fetched chunks more eagerly
- Fix heartbeats fetch ordering, was causing some heartbeats to be lost in large batches
=> Heartbeat processor fixes and tweaks

p2p/src/network/yamux/p2p_network_yamux_reducer.rs, p2p/src/network/yamux/p2p_network_yamux_state.rs
* Changed window size logic so window size can increase more than 256kb
* Changed logic with outgoing data to send packets with size 0
* Changed logic to send window update after half our window is consumed instead of only 64kb being left
=> Fixed the issue with pending queue in yamux

Cargo.lock, core/Cargo.toml, core/src/lib.rs, core/src/p2p.rs, core/src/transaction/mod.rs, node/src/action_kind.rs, node/src/rpc/rpc_reducer.rs, node/src/snark_pool/candidate/snark_pool_candidate_actions.rs, node/src/snark_pool/candidate/snark_pool_candidate_reducer.rs, node/src/snark_pool/snark_pool_reducer.rs, node/src/state.rs, node/src/transaction_pool/candidate/transaction_pool_candidate_reducer.rs, node/src/transaction_pool/transaction_pool_actions.rs, node/src/transaction_pool/transaction_pool_effects.rs, node/src/transaction_pool/transaction_pool_reducer.rs, p2p/src/channels/snark/p2p_channels_snark_actions.rs, p2p/src/channels/snark/p2p_channels_snark_reducer.rs, p2p/src/channels/transaction/p2p_channels_transaction_actions.rs, p2p/src/channels/transaction/p2p_channels_transaction_reducer.rs, p2p/src/network/pubsub/mod.rs, p2p/src/network/pubsub/p2p_network_pubsub_actions.rs, p2p/src/network/pubsub/p2p_network_pubsub_reducer.rs, p2p/src/network/pubsub/p2p_network_pubsub_state.rs, p2p/src/p2p_state.rs, snark/src/user_command_verify/snark_user_command_verify_actions.rs, snark/src/user_command_verify/snark_user_command_verify_reducer.rs, snark/src/user_command_verify/snark_user_command_verify_state.rs, snark/src/work_verify/snark_work_verify_actions.rs, snark/src/work_verify/snark_work_verify_reducer.rs, snark/src/work_verify/snark_work_verify_state.rs
Resolves #1055, continuation of #1001
=> Added broadcast delay for snarks and transactions until they are fully vertified

node/src/action_kind.rs, node/src/snark_pool/candidate/snark_pool_candidate_actions.rs, node/src/state.rs, node/src/transaction_pool/candidate/transaction_pool_candidate_actions.rs, node/src/transaction_pool/candidate/transaction_pool_candidate_reducer.rs, node/src/transaction_pool/candidate/transaction_pool_candidate_state.rs, node/src/transaction_pool/transaction_pool_reducer.rs, p2p/src/channels/transaction/p2p_channels_transaction_reducer.rs, p2p/src/p2p_state.rs
Solves: #1067
* Updated `TransactionPoolCandidatesState` to have transactions grouped by pubsub message id
* Changed flow for transactions received in pubsub to be stored in candidate state before before being processed
=> Changed action flow for transaction in pubsub

Cargo.lock, cli/Cargo.toml, cli/src/main.rs
<details>
<summary>Example when the main thread panics:</summary>
```
thread 'main' panicked at node/src/ledger/ledger_manager.rs:438:18:
get_accounts failed
0:     0x55f1b7788089 - backtrace::backtrace::libunwind::trace::hda77ddeedf7bc2d6
at /home/sebastien/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.69/src/backtrace/libunwind.rs:93:5
backtrace::backtrace::trace_unsynchronized::h061fee87c82cf614
at /home/sebastien/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.69/src/backtrace/mod.rs:66:5
backtrace::backtrace::trace::h2225c7518a9fac40
at /home/sebastien/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/backtrace-0.3.69/src/backtrace/mod.rs:53:14
backtrace::capture::Backtrace::create::h73e8bf6078684b8f
at …
```
=> Display panics from other threads when main thread panics

node/src/action_kind.rs, node/src/effects.rs, node/src/logger/logger_effects.rs, node/src/transition_frontier/candidate/transition_frontier_candidate_actions.rs, node/src/transition_frontier/candidate/transition_frontier_candidate_reducer.rs, node/src/transition_frontier/candidate/transition_frontier_candidate_state.rs, node/src/transition_frontier/sync/transition_frontier_sync_actions.rs, node/src/watched_accounts/watched_accounts_actions.rs
After receiving a new block from peer, check consensus first, if it's better than the current best tip, only then proceed to do a more expensive proof verification.
re: #998
=> Transition Frontier: do cheap consensus first then expensive verification

core/src/block/prevalidate.rs, node/src/transition_frontier/candidate/transition_frontier_candidate_reducer.rs, node/src/transition_frontier/candidate/transition_frontier_candidate_state.rs
As pointed out by @tizoc , this pr: #1090 introduced a bug which would cause too early received blocks to be invalidated forever.
This pr fixes that.
=> Fix(transition_frontier/candidate): don't forever invalidate early received blocks

Cargo.lock, ledger/src/proofs/block.rs, ledger/src/proofs/merge.rs, ledger/src/proofs/mod.rs, ledger/src/proofs/prover.rs, ledger/src/proofs/public_input/prepared_statement.rs, ledger/src/proofs/step.rs, ledger/src/proofs/transaction.rs, ledger/src/proofs/unfinalized.rs, ledger/src/proofs/verification.rs, ledger/src/proofs/wrap.rs, ledger/src/proofs/zkapp.rs, node/common/Cargo.toml, node/common/src/service/block_producer/mod.rs, node/testing/src/service/mod.rs
To debug block proof generation
=> Add error + backtrace to `failed_block_proof_input_HASH.binprot`

.github/workflows/docker.yaml
Needed to produce a version from git tag when building the docker images.
=> fix(ci): When building the docker image, fetch the current tag 

core/src/channels.rs, node/common/src/service/block_producer/mod.rs, node/common/src/service/block_producer/vrf_evaluator.rs, node/common/src/service/event_receiver.rs, node/common/src/service/p2p.rs, node/common/src/service/service.rs, node/common/src/service/snarks.rs, node/src/ledger/ledger_manager.rs, node/src/rpc/mod.rs, node/src/rpc_effectful/rpc_effectful_effects.rs, node/src/service.rs, node/testing/src/service/mod.rs, p2p/src/service_impl/mio/mod.rs, p2p/src/service_impl/mod.rs, p2p/src/service_impl/webrtc/mod.rs, p2p/testing/src/cluster.rs, p2p/testing/src/rust_node.rs, p2p/testing/src/service.rs
In rust node, we have queues/channels between state machine and services. It would be useful to inspect current state of those queues at any given moment.
```
{
"events": 0,
"snark_block_verify": 0,
"ledger": 0,
"vrf_evaluator": 0,
"block_prover": 0,
"p2p_webrtc": 10,
"rpc": 0
}
```
=> Status Rpc: extend response to include current service queues

ledger/src/port_ocaml/hash.rs, macros/src/action_event.rs, node/common/src/service/builder.rs, node/common/src/service/service.rs, node/common/src/service/snark_worker.rs, node/src/event_source/event_source_effects.rs, node/src/external_snark_worker_effectful/external_snark_worker_effectful_effects.rs, node/src/external_snark_worker_effectful/external_snark_worker_service.rs, node/src/recorder/recorder.rs, node/src/snark_pool/candidate/snark_pool_candidate_actions.rs, node/src/snark_pool/snark_pool_reducer.rs, node/src/snark_pool/snark_pool_state.rs, node/src/stats/stats_sync.rs, node/src/transition_frontier/sync/transition_frontier_sync_actions.rs, node/src/transition_frontier/sync/transition_frontier_sync_reducer.rs, node/src/transition_frontier/transition_frontier_actions.rs, node/src/transition_frontier/transition_frontier_effects.rs, node/testing/src/service/mod.rs, p2p/src/channels/best_tip/p2p_channels_best_tip_actions.rs, p2p/src/channels/streaming_rpc/p2p_channels_streaming_rpc_actions.rs, p2p/src/connection/outgoing/p2p_connection_outgoing_actions.rs, p2p/src/network/rpc/p2p_network_rpc_state.rs, p2p/src/network/scheduler/p2p_network_scheduler_actions.rs, p2p/src/peer/p2p_peer_actions.rs, p2p/testing/src/redux.rs
Make the Rust based snark worker work again.
We used to use ocaml based prover since we didn't have that logic in Rust, but now we do. We can use that to generate proofs for the snark work.
Since snark work can be fairly computationally expensive, eventually the goal would be to run this worker in an external process, so that we can kill it in order to cancel it.
In case of the web node, unlike native threads, it's thread can be [terminated](https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate), so we'll use that there in the future.
=> Rust based Snark Worker

node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_actions.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_reducer.rs, node/src/block_producer/vrf_evaluator/block_producer_vrf_evaluator_state.rs
This caused the epoch evaluation readiness check to incorrectly assume that the next epoch had already been evaluating, preventing won slot search from running.
=> fix(vrf-evaluator): Fix interruption of won slots search at epoch boundaries

.github/workflows/ci.yaml
20.04 images are not available anymore.
To be able to run our binaries built on Ubuntu 22.04 inside the Mina Debian Bullseye image, libssl3 gets installed before running the tests.
=> chore(ci): Upgrade jobs to use Ubuntu 22.04

node/native/src/node/builder.rs, node/testing/src/hosts.rs, p2p/src/connection/outgoing/mod.rs
Don't perform DNS resolution during parsing, instead perform all name resolutions when building the list, and skip peers for which the address cannot be resolved.
=> fix(p2p): Do not fail when an initial peer address cannot be resolved

Makefile
Fix https://github.com/o1-labs/openmina/issues/1199
=> Makefile: add target to run an archive node

.github/workflows/ci.yaml
=> CI: remove code related to decomissionned k8s nodes

CLAUDE.md
Add CLAUDE.md with makefile commands for formatting:
- make format-md for markdown files
- make format for Rust/TOML files
- make check-md and make check-format for verification
Include commit guidelines:
- Never add Claude as co-author
- Never use emojis in commit messages
- Always wrap titles and body at 80 characters
=> docs: add Claude formatting instructions

Makefile, ledger/src/base.rs, ledger/src/generators/zkapp_command_builder.rs, ledger/src/scan_state/fee_excess.rs, ledger/src/scan_state/transaction_logic.rs, node/src/ledger/ledger_service.rs, p2p/src/p2p_state.rs, p2p/testing/src/utils.rs
`make docs-rust` was generating quite a few warnings with broken links. This PR fixes broken internal links.
=> Fix broken links for cargo doc

.github/workflows/test-docs-scripts.yml, CHANGELOG.md, website/docs/developers/scripts/update-ocaml-node.sh, website/docs/developers/updating-ocaml-node.md
Reviewer can check commit by commit.
=> Scripts to update OCaml node

.github/workflows/lint.yml, CHANGELOG.md, Makefile, frontend/docker/startup.sh, frontend/scripts/download-webnode.sh, producer-dashboard/docker/init-db/init-db.sh
=> CI: add shellcheck

.github/workflows/test-docs-scripts.yml, website/docs/developers/scripts/setup/install-system-deps-macos.sh, website/docs/developers/scripts/setup/install-system-deps.sh
- Add shellcheck to Ubuntu/Debian system dependencies script
- Add shellcheck to macOS system dependencies script via Homebrew  
- Update CI workflow to verify shellcheck installation in doc testing
This ensures shellcheck is available for developers following the setup documentation and validates the installation works correctly across all supported platforms.
=> docs: add shellcheck to system dependencies installation

Makefile, cli/src/commands/node/mod.rs, website/docs/node-runners/building-from-source.md
- Redirect build instructions from Node Runners to Developer Getting Started guide for consistency and maintainability
- Add run-node Makefile target with NETWORK and VERBOSITY variables
- Focus Node Runners documentation on binary execution and Makefile variables only
- Document comprehensive CLI parameters in Rust code with examples
- Add detailed multiaddr format documentation for peer configuration
- Link to Rust API documentation for complete parameter reference
- Reference comprehensive Archive Node documentation
- Fix parameter name from log-level to verbosity to match actual CLI
This creates a cleaner separation where build instructions are centralized in the tested Developer guide, while Node Runners focuses on runtime configuration using simple Makefile targets.
=> docs: unify node runner documentation with makefile targets

.github/workflows/ci.yaml, CHANGELOG.md
Fix #1304
See
https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstrategyfail-fast
=> CI: set fail-fast to false to prevent cancelling other jobs

snark/src/block_verify/mod.rs, snark/src/block_verify_effectful/mod.rs, snark/src/lib.rs, snark/src/merkle_path/mod.rs, snark/src/user_command_verify/mod.rs, snark/src/work_verify/mod.rs, website/docs/developers/architecture.md
See https://github.com/o1-labs/mina-rust/issues/1298
=> Website + snark crate documentation

poseidon/src/hash.rs, poseidon/tests/test_hash_params.rs
In a follow-up PR, I will be changing the implementation of `param_to_field_impl` to get rid of `FromBytes`, which comes from a fork of an arkworks dependency. This is part of https://github.com/o1-labs/mina-rust/issues/1153.
=> poseidon: add regtest for hash params

.github/scripts/test-graphql-remote/wait-for-graphql.sh, .github/workflows/test-graphql-compatibility.yml, CHANGELOG.md, website/docs/developers/scripts/update-ocaml-node.sh
This will be useful to check that we stay compatible with the OCaml node, and in particular that all GraphQL endpoints tested with the Rust nodes are also implemented in the OCaml node.
Complementary to https://github.com/o1-labs/mina-rust/pull/1466
=> CI: add workflow to test GraphQL queries against OCaml node

CHANGELOG.md, website/docs/node-operators/archive-node.md, website/docs/node-operators/block-producer.md, website/docs/node-operators/join-devnet.md, website/sidebars.ts, website/src/pages/index.tsx
=> Website: add a "Join devnet" CTA button and section

website/docs/developers/frontend/node-dashboard.mdx, website/docs/node-operators/infrastructure/frontend.mdx
=> Website: update o1Labs infrastructure section with the node dashboard link 

.github/scripts/verify-code-references.sh, .github/workflows/docs.yaml, ledger/src/scan_state/transaction_logic.rs
This will be used in a next PR adding developers documentation about zkApps.
=> Ledger/transaction_logic: add fields doc

node/native/src/graphql/mod.rs
Warnings appear when running `make docs-build`.
=> Node/graphql: remove unused structures
